language: java
jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2

deploy:
  provider: script
  script: "mvn --settings .travis.settings.xml -DskipTests=true -B clean deploy"
  skip_cleanup: true
  on:
    tags: true
    